default_stages: [commit]

repos:

  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus, --keep-percent-format]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - |-
            pycodestyle ==2.7.0
          - |-
            pyflakes ==2.3.1
          - |-
            flake8-bandit ==2.1.2
          - |-
            bandit ==1.7.0
          - |-
            flake8-bugbear ==21.4.3
          - |-
            flake8-comprehensions ==3.7.0
          - |-
            flake8-docstrings ==1.6.0
          - |-
            pydocstyle ==6.1.1

  - repo: local
    hooks:

      - id: mypy
        name: mypy
        language: python
        additional_dependencies:
          - |-
            venv-run ==0.1.0
        entry: venv-run mypy
        types: [python]
        require_serial: true

      - id: pytype
        name: pytype
        language: python
        language_version: "3.8"
        additional_dependencies:
          - |-
            venv-run ==0.1.0
        entry: venv-run pytype
        types: [python]
        require_serial: true

      - id: pylint
        name: pylint
        language: python
        additional_dependencies:
          - |-
            venv-run ==0.1.0
        entry: venv-run pylint
        types: [python]
        require_serial: true

  - repo: https://github.com/crate-ci/typos
    rev: v1.1.7
    hooks:
      - id: typos

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: 0.9.0
    hooks:
      - id: pymarkdown
        exclude: ^CHANGELOG\.md$
